apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: modusynth
  name: frontend-ingress
  labels:
    app: modusynth
spec:
  rules:
    - http:
        paths:
          - path: "(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80