apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: modusynth
  name: frontend-deployment
  labels:
    app: modusynth-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modusynth-gui
  template:
    metadata:
      labels:
        app: modusynth
    spec:
      dnsPolicy: Default
      containers:
        - name: modusynth-frontend
          image: virtuatable/modusynth-frontend:<VERSION>
          args:
            - web
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: url