apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: modusynth
  name: frontend-deployment
  labels:
    app: modusynth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modusynth
  template:
    metadata:
      labels:
        app: modusynth
    spec:
      dnsPolicy: Default
      containers:
        - name: modusynth-frontend
          image: virtuatable/modusynth-frontend:<VERSION>
          args:
            - web
          ports:
            - containerPort: 3000
          env:
            - name: RACK_ENV
              value: production
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-uri