apiVersion: v1
kind: Service
metadata:
  namespace: <NAMESPACE>
  name: frontend-service
  labels:
    app: modusynth-gui
spec:
  selector:
    app: modusynth-gui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000