apiVersion: v1
kind: Service
metadata:
  namespace: modusynth
  name: frontend-service
  labels:
    app: modusynth
spec:
  selector:
    app: modusynth
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000